### ISSUE TITLE
`iotedgedev build` failing in a py27 environment 

### ISSUE THREAD

**Issue by druttka** [Azure/iotedgedev#187]
Labeling as a question and self-assigning in case this is limited to my environment, but I don't want to lose track of it. Running tox, I finally have a fully green result for py36. However, test_e2e still hits an error when running on py27. This also happens for me at `iotedgedev build` time as an end user in a py27 environment (see further comment below)

AssertionError occurs because of an underlying `<Result TypeError('environment can only contain strings',)>.output`

```
=================================== ERRORS ====================================
_________________________ ERROR at setup of test_e2e __________________________

request = <SubRequest 'test_push_modules' for <Function 'test_e2e'>>

    @pytest.fixture
    def test_push_modules(request):

        os.chdir(test_solution_dir)

        cli = __import__("iotedgedev.cli", fromlist=['main'])
        runner = CliRunner()
        result = runner.invoke(cli.main, ['push'])
        print(result.output)

>       assert 'BUILD COMPLETE' in result.output
E       AssertionError: assert 'BUILD COMPLETE' in '\n=========================================\n======== PROCESSING CONFIG FILES ========\n================================...yright (C) Microsoft Corporation. All rights reserved.\nBUILDING DOCKER IMAGE: localhost:5000/csharpmodule:0.0.1-amd64\n'
E        +  where '\n=========================================\n======== PROCESSING CONFIG FILES ========\n================================...yright (C) Microsoft Corporation. All rights reserved.\nBUILDING DOCKER IMAGE: localhost:5000/csharpmodule:0.0.1-amd64\n' = <Result TypeError('environment can only contain strings',)>.output

..\..\..\test_iotedgedev.py:145: AssertionError
_________________________ ERROR at setup of test_node _________________________

request = <SubRequest 'test_push_modules' for <Function 'test_node'>>

    @pytest.fixture
    def test_push_modules(request):

        os.chdir(test_solution_dir)

        cli = __import__("iotedgedev.cli", fromlist=['main'])
        runner = CliRunner()
        result = runner.invoke(cli.main, ['push'])
        print(result.output)

>       assert 'BUILD COMPLETE' in result.output
E       AssertionError: assert 'BUILD COMPLETE' in '\n=========================================\n======== PROCESSING CONFIG FILES ========\n================================...yright (C) Microsoft Corporation. All rights reserved.\nBUILDING DOCKER IMAGE: localhost:5000/csharpmodule:0.0.1-amd64\n'
E        +  where '\n=========================================\n======== PROCESSING CONFIG FILES ========\n================================...yright (C) Microsoft Corporation. All rights reserved.\nBUILDING DOCKER IMAGE: localhost:5000/csharpmodule:0.0.1-amd64\n' = <Result TypeError('environment can only contain strings',)>.output

..\..\..\test_iotedgedev.py:145: AssertionError
===================== 22 passed, 2 error in 15.56 seconds =====================
```

**Comment by druttka** [comment]
Using iotedgedev as an end user on py27, I got a very similar error during `iotedgedev build`. I haven't taken a close look yet, but it seems to fail during the docker build. Same steps succeed in a py36 environment.

```
(py27) E:\iotedgedev>cd ..

(py27) E:\>mkdir py27edgetest

(py27) E:\>cd py27edgetest

(py27) E:\py27edgetest>iotedgedev solution

=====================================================
======== CREATING AZURE IOT EDGE SOLUTION: . ========
=====================================================

AZURE IOT EDGE SOLUTION CREATED


(py27) E:\py27edgetest>iotedgedev build

=======================================
======== ENVIRONMENT VARIABLES ========
=======================================

Environment Variables loaded from: .env (E:\py27edgetest\.env)

=========================================
======== PROCESSING CONFIG FILES ========
=========================================

Expanding 'deployment.template.json' to 'config\deployment.json'
Expanding 'runtime.template.json' to 'config\runtime.json'


=================================================
======== INITIALIZING CONTAINER REGISTRY ========
=================================================

REGISTRY: localhost:5000
Looking for local 'registry' container
Found local 'registry' container


==================================
======== BUILDING MODULES ========
==================================

BUILDING MODULE: modules\filtermodule
2.1.300
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.17
PROCESSING DOCKER FILE: ./Dockerfile.amd64.debug
PUBLISHING MODULE: modules\filtermodule
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
BUILDING DOCKER IMAGE: localhost:5000/filtermodule:0.0.1-amd64.debug
Traceback (most recent call last):
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\Scripts\iotedgedev-script.py", line 11, in <module>
    load_entry_point('iotedgedev', 'console_scripts', 'iotedgedev')()
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "e:\iotedgedev\iotedgedev\cli.py", line 117, in build
    ctx.invoke(modules, build=True, push=push, deploy=deploy)
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "e:\iotedgedev\iotedgedev\cli.py", line 457, in modules
    mod.build()
  File "e:\iotedgedev\iotedgedev\modules.py", line 19, in build
    self.build_push(no_push=True)
  File "e:\iotedgedev\iotedgedev\modules.py", line 77, in build_push
    build_result = self.dock.docker_client.images.build(tag=image_destination_name, path=".", dockerfile=docker_file_name, buildargs={"EXE_DIR": mod_proc.exe_dir})
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\site-packages\docker\models\images.py", line 175, in build
    resp = self.client.api.build(**kwargs)
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\site-packages\docker\api\build.py", line 239, in build
    self._set_auth_headers(headers)
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\site-packages\docker\api\build.py", line 276, in _set_auth_headers
    self._auth_configs, registry
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\site-packages\docker\auth.py", line 94, in resolve_authconfig
    authconfig, registry, store_name
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\site-packages\docker\auth.py", line 123, in _resolve_authconfig_credstore
    data = store.get(registry)
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\site-packages\dockerpycreds\store.py", line 35, in get
    data = self._execute('get', server)
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\site-packages\dockerpycreds\store.py", line 79, in _execute
    stdout=subprocess.PIPE, env=env,
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Users\daruttka\AppData\Local\conda\conda\envs\py27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

**Comment by yorek** [comment]
I'm having exactly the same problem, using Python 2.7.14

**Comment by druttka** [comment]
Thanks for confirming. I'm going to move this from "question" to "bug," then. I have temporarily unassigned myself, but will re-assign myself if I have a chance to pick this back up.

**Comment by druttka** [comment]
It looks like `environment can only contain strings` from `subprocess` is fairly common, and one of the usual suspects is Unicode strings making it into the env. 

https://github.com/pallets/werkzeug/issues/467#issuecomment-53996277
https://github.com/conda/conda-build/pull/824
http://trac.osgeo.org/grass/ticket/2532

@yorek  - were you on Windows when you got this error?

**Comment by jongio** [comment]
I'm researching this.

**Comment by jongio** [comment]
#230 fixes this.

**Comment by acumino** [comment]
I am using Windows 10 and python 3.7 and getting the same error. #AnySolution?

**Comment by sivakotich** [comment]
> 
> 
> I am using Windows 10 and python 3.7 and getting the same error. #AnySolution?

Observing the same using Windows 10 and python 3.8. Please let us know of any solution,

**Comment by sivakotich** [comment]
> 
> 
> > I am using Windows 10 and python 3.7 and getting the same error. #AnySolution?
> 
> Observing the same using Windows 10 and python 3.8. Please let us know of any solution,

Update .repo/repo/git_command.py like below -
In the __init__ function of GitCommand Class, just change env = env with below.
                           env = dict( [i for i in os.environ.items()] + [(u'HGENCODING', u'utf-8')]),
it worked for me.
