### ISSUE TITLE
Unable to use a shared project

### ISSUE THREAD

**Issue by StephanBis** [Azure/iotedgedev#207]
I have two modules which build and deploy just fine. But they both have shared code which I want to pull to a seperate "Shared" project. The modules have a reference to the shared project and everything seems to work. But when I want to build the docker image I get this trace:

```
PROCESSING DOCKER FILE: ./Dockerfile
    PUBLISHING MODULE: modules/Valid.PrivacyCrawler.Crawlers
    Microsoft (R) Build Engine version 15.5.179.9764 for .NET Core
    Copyright (C) Microsoft Corporation. All rights reserved.
    BUILDING DOCKER IMAGE: privacycrawler.azurecr.io/valid.privacycrawler.crawlers:0.0.12-amd64
    Traceback (most recent call last):
      File "/usr/local/bin/iotedgedev", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/iotedgedev/cli.py", line 132, in push
        ctx.invoke(modules, push=push, deploy=deploy, no_build=no_build)
      File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/iotedgedev/cli.py", line 454, in modules
        mod.push(no_build=no_build)
      File "/usr/local/lib/python2.7/dist-packages/iotedgedev/modules.py", line 22, in push
        self.build_push(no_build=no_build)
      File "/usr/local/lib/python2.7/dist-packages/iotedgedev/modules.py", line 77, in build_push
        build_result = self.dock.docker_client.images.build(tag=image_destination_name, path=".", dockerfile=docker_file_name, buildargs={"EXE_DIR": mod_proc.exe_dir})
      File "/usr/local/lib/python2.7/dist-packages/docker/models/images.py", line 183, in build
        raise BuildError(chunk['error'], result_stream)
    docker.errors.BuildError: The command '/bin/sh -c dotnet publish -c Release -o out' returned a non-zero code: 1
```

When I duplicate the code and don't use the shared project it just builds the modules without a problem. Is having a shared project, which is .NET core just like the modules, not supported? I can use NuGet packages (like Newtonsoft.JSON) without a problem.

**Comment by jongio** [comment]
@StephanBis - I'm updating the readme right now, but at the moment iotedgedev does not work with GA bits.  Our target is to release a GA compat version by mid-august.

@LazarusX - Can you look into using shared projects?

**Comment by StephanBis** [comment]
Thank you for your reply. What exactly do you mean wirh GA? Has this something to do with using shared projects?
