### ISSUE TITLE
iotedgedev deploy: AttributeError: 'EnvVars' object has no attribute 'IOTHUB_CONNECTION_INFO'

### ISSUE THREAD

**Issue by jongio** [Azure/iotedgedev#234]
iotedgedev solution create test
cd test
iotedgedev build
iotedgedev push --deploy

```
=========================================
======== DEPLOYING CONFIGURATION ========
=========================================

Traceback (most recent call last):
  File "c:\python36\.virtualenv\py3\Scripts\iotedgedev-script.py", line 11, in <module>
    load_entry_point('iotedgedev', 'console_scripts', 'iotedgedev')()
  File "c:\python36\.virtualenv\py3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python36\.virtualenv\py3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python36\.virtualenv\py3\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python36\.virtualenv\py3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python36\.virtualenv\py3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python36\.virtualenv\py3\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\jon\dropbox\code\github\jongio\iotedgedev\iotedgedev\cli.py", line 194, in push
    ctx.invoke(deploy)
  File "c:\python36\.virtualenv\py3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\jon\dropbox\code\github\jongio\iotedgedev\iotedgedev\cli.py", line 204, in deploy
    edge.deploy()
  File "c:\users\jon\dropbox\code\github\jongio\iotedgedev\iotedgedev\edge.py", line 13, in deploy
    self.envvars.verify_envvar_has_val("IOTHUB_CONNECTION_INFO", self.envvars.IOTHUB_CONNECTION_INFO)
  File "c:\users\jon\dropbox\code\github\jongio\iotedgedev\iotedgedev\envvars.py", line 184, in __getattribute__
    raise e
  File "c:\users\jon\dropbox\code\github\jongio\iotedgedev\iotedgedev\envvars.py", line 179, in __getattribute__
    return object.__getattribute__(self, name)
AttributeError: 'EnvVars' object has no attribute 'IOTHUB_CONNECTION_INFO'
```

If I add a iothub connection string in .env I get this

```
=========================================
======== DEPLOYING CONFIGURATION ========
=========================================

Traceback (most recent call last):
  File "c:\python36\.virtualenv\py3\Scripts\iotedgedev-script.py", line 11, in <module>
    load_entry_point('iotedgedev', 'console_scripts', 'iotedgedev')()
  File "c:\python36\.virtualenv\py3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python36\.virtualenv\py3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python36\.virtualenv\py3\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python36\.virtualenv\py3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python36\.virtualenv\py3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python36\.virtualenv\py3\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\jon\dropbox\code\github\jongio\iotedgedev\iotedgedev\cli.py", line 194, in push
    ctx.invoke(deploy)
  File "c:\python36\.virtualenv\py3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\jon\dropbox\code\github\jongio\iotedgedev\iotedgedev\cli.py", line 204, in deploy
    edge.deploy()
  File "c:\users\jon\dropbox\code\github\jongio\iotedgedev\iotedgedev\edge.py", line 14, in deploy
    self.envvars.verify_envvar_has_val("DEVICE_CONNECTION_INFO", self.envvars.DEVICE_CONNECTION_INFO)
  File "c:\users\jon\dropbox\code\github\jongio\iotedgedev\iotedgedev\envvars.py", line 184, in __getattribute__
    raise e
  File "c:\users\jon\dropbox\code\github\jongio\iotedgedev\iotedgedev\envvars.py", line 179, in __getattribute__
    return object.__getattribute__(self, name)
AttributeError: 'EnvVars' object has no attribute 'DEVICE_CONNECTION_INFO'
```

Adding both fixes the issue.

Likely a bug in the way we check for existence of envvars.

**Comment by jongio** [comment]
Fixed #235
