### ISSUE TITLE
iotedgedev v0.82.0 docker image error in edgeHubDev 

### ISSUE THREAD

**Issue by mridup** [Azure/iotedgedev#317]
- iotedgedev Version: v0.82.0
- Python Version: v3.6.5
- Pip Version: 18.0
- Development machine OS Version: Ubuntu 16.04 x64
- IoT Edge device OS Version: Ubuntu 16.04 x64

Steps to Reproduce:
1. Followed by running the quickstart "docker for iotedgedev"
2. After Step 7. I checked the docker logs for iotedgeHubDev container. It shows errors as follows:
```
iotedgedev@9fbebd2eaead:/home/iotedge/sampledev$ sudo docker logs edgeHubDev
[2018-09-11 12:22:05 : Starting Edge Hub
[09/11/2018 12:22:07.910 PM] Edge Hub Main()
2018-09-11 12:22:12.251 +00:00 [INF] - Starting Edge Hub
2018-09-11 12:22:12.312 +00:00 [INF] - Version - 1.0.1.15962126 (6e5e86dcf0c9a3732fc72a64d9ec9b0fcb2d6fad)
2018-09-11 12:22:12.313 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

2018-09-11 12:22:12.313 +00:00 [INF] - Installing intermediate certificates.
2018-09-11 12:22:12.522 +00:00 [INF] - Attempting to connect to IoT Hub for client iotedge-x64/$edgeHub via AMQP...
2018-09-11 12:22:12.588 +00:00 [INF] - Connected to IoT Hub for client iotedge-x64/$edgeHub via AMQP, with client operation timeout 60000.
2018-09-11 12:22:12.600 +00:00 [INF] - Created cloud connection for client iotedge-x64/$edgeHub
2018-09-11 12:22:12.602 +00:00 [INF] - New cloud connection created for device iotedge-x64/$edgeHub
2018-09-11 12:22:12.612 +00:00 [INF] - Initializing configuration
2018-09-11 12:22:13.906 +00:00 [INF] - Created persistent store at /tmp/edgeHub
2018-09-11 12:22:13.913 +00:00 [INF] - Created new message store
2018-09-11 12:22:13.913 +00:00 [INF] - Started task to cleanup processed and stale messages
2018-09-11 12:22:14.648 +00:00 [INF] - Set the following 2 route(s) in edge hub
2018-09-11 12:22:14.649 +00:00 [INF] - r1: FROM /messages/modules/tempSensor/outputs/temperatureOutput INTO BrokeredEndpoint("/modules/sampledev/inputs/input1")
2018-09-11 12:22:14.649 +00:00 [INF] - r2: FROM /messages/modules/sampledev/outputs/* INTO $upstream
2018-09-11 12:22:14.651 +00:00 [INF] - Updated message store TTL to -1 seconds
2018-09-11 12:22:14.651 +00:00 [INF] - Updated the edge hub store and forward configuration
2018-09-11 12:22:14.652 +00:00 [INF] - Initialized edge hub configuration
2018-09-11 12:22:14.923 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
2018-09-11 12:22:14.939 +00:00 [INF] - Starting MQTT head
2018-09-11 12:22:15.048 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
2018-09-11 12:22:15.173 +00:00 [INF] - Starting AMQP head
2018-09-11 12:22:15.187 +00:00 [INF] - Started MQTT head
2018-09-11 12:22:15.307 +00:00 [INF] - Started AMQP head
2018-09-11 12:22:15.311 +00:00 [INF] - Starting HTTP head
2018-09-11 12:22:15.545 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
2018-09-11 12:22:15.591 +00:00 [INF] - Creating key {80a9e17a-28c4-4e95-9c79-4457056e8698} with creation date 2018-09-11 12:22:15Z, activation date 2018-09-11 12:22:15Z, and expiration date 2018-12-10 12:22:15Z.
2018-09-11 12:22:15.748 +00:00 [WRN] - No XML encryptor configured. Key {80a9e17a-28c4-4e95-9c79-4457056e8698} may be persisted to storage in unencrypted form.
2018-09-11 12:22:15.760 +00:00 [INF] - Writing data to file '"/home/edgehubuser/.aspnet/DataProtection-Keys/key-80a9e17a-28c4-4e95-9c79-4457056e8698.xml"'.
2018-09-11 12:22:16.317 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
2018-09-11 12:22:16.362 +00:00 [INF] - Started HTTP head
2018-09-11 12:22:16.956 +00:00 [INF] - Attempting to connect to IoT Hub for client iotedge-x64/tempSensor via AMQP...
2018-09-11 12:22:16.962 +00:00 [INF] - Connected to IoT Hub for client iotedge-x64/tempSensor via AMQP, with client operation timeout 60000.
2018-09-11 12:22:16.972 +00:00 [INF] - Created cloud connection for client iotedge-x64/tempSensor
2018-09-11 12:22:16.972 +00:00 [INF] - New cloud connection created for device iotedge-x64/tempSensor
2018-09-11 12:22:18.223 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 10dcbf64
2018-09-11 12:22:20.715 +00:00 [INF] - New token requested by client iotedge-x64/tempSensor, but using existing token as it is usable.
2018-09-11 12:22:24.315 +00:00 [WRN] - Error opening IotHub connection for device iotedge-x64/tempSensor
Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: Put token failed. status-code: 401, status-description: The specified SAS token has an invalid signature. It does not match either the primary or secondary key..
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass26_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 132
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 112
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.OpenAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 61
2018-09-11 12:22:24.418 +00:00 [WRN] - Error authenticating token received on the Cbs link for iotedge-x64/tempSensor
2018-09-11 12:22:26.045 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 7fa65c6f
2018-09-11 12:22:28.471 +00:00 [INF] - Attempting to connect to IoT Hub for client iotedge-x64/tempSensor via AMQP...
2018-09-11 12:22:28.471 +00:00 [INF] - Connected to IoT Hub for client iotedge-x64/tempSensor via AMQP, with client operation timeout 60000.
2018-09-11 12:22:28.488 +00:00 [ERR] - Error closing cloud proxy 8863caba-cf41-47b0-b07d-3f33426992a6 for device iotedge-x64/tempSensor
Microsoft.Azure.Devices.Client.Exceptions.AssertionFailedException: An unexpected failure occurred. Applications should not attempt to handle this error. For diagnostic purposes, this English message is associated with the failure: The number of devices should be greater than zero.
   at Microsoft.Azure.Devices.Client.Fx.AssertAndThrow(String description)
   at Microsoft.Azure.Devices.Client.IotHubDeviceScopeConnectionPool.RemoveDeviceFromConnection(IotHubDeviceMuxConnection iotHubDeviceMuxConnection, String deviceId)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.CloseAsync()
   at Microsoft.Azure.Devices.Client.Transport.GateKeeperDelegatingHandler.CloseAsync()
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.CloseAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 44
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.CloseAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 46
2018-09-11 12:22:28.492 +00:00 [INF] - New cloud connection created for device iotedge-x64/tempSensor
2018-09-11 12:22:28.494 +00:00 [INF] - New token requested by client iotedge-x64/tempSensor, but using existing token as it is usable.
2018-09-11 12:22:28.503 +00:00 [WRN] - Error in connection established callback for client iotedge-x64/tempSensor - System.AggregateException One or more errors occurred. (A task was canceled.)
2018-09-11 12:22:30.394 +00:00 [INF] - Exiting disconnected state
2018-09-11 12:22:30.398 +00:00 [INF] - Entering connected state
2018-09-11 12:22:30.562 +00:00 [INF] - New device connection for device iotedge-x64/tempSensor
2018-09-11 12:22:30.563 +00:00 [INF] - Bind device proxy for device iotedge-x64/tempSensor
2018-09-11 12:22:30.565 +00:00 [INF] - Initialized AMQP connection handler for iotedge-x64/tempSensor
2018-09-11 12:22:30.579 +00:00 [INF] - Opened link Events for iotedge-x64/tempSensor
2018-09-11 12:22:30.721 +00:00 [INF] - Opened link MethodReceiving for iotedge-x64/tempSensor
2018-09-11 12:22:31.607 +00:00 [INF] - Opened link MethodSending for iotedge-x64/tempSensor
2018-09-11 12:22:31.670 +00:00 [INF] - Opened link ModuleMessages for iotedge-x64/tempSensor
2018-09-11 12:22:32.214 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:22:33.227 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:22:35.116 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:22:39.000 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:22:42.035 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 4955ff6b
2018-09-11 12:22:46.384 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:23:01.775 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:23:14.023 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 225a92b3
2018-09-11 12:23:34.964 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:24:20.028 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 1d40b719
2018-09-11 12:24:34.964 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:25:34.968 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:26:31.024 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 7bb6de84
2018-09-11 12:26:34.968 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:27:34.973 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:28:33.790 +00:00 [INF] - Exiting connected state
2018-09-11 12:28:33.791 +00:00 [INF] - Entering unreachable state
2018-09-11 12:28:34.975 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:29:33.802 +00:00 [INF] - Entering disconnected state
2018-09-11 12:29:34.976 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:30:34.978 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:30:54.023 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 33ccf5c4
2018-09-11 12:31:34.981 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:31:42.878 +00:00 [WRN] - Error calling IotHub for connectivity test
System.InvalidOperationException: Service rejected the message with status: 400
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass26_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 132
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 112
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.UpdateReportedPropertiesAsync(IMessage reportedPropertiesMessage) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 121
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceConnectivityManager.ConnectivityChecker.Check() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceConnectivityManager.cs:line 187
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceConnectivityManager.CheckConnectivity() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceConnectivityManager.cs:line 156
2018-09-11 12:32:34.984 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:33:34.984 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:33:35.089 +00:00 [INF] - Exiting disconnected state
2018-09-11 12:33:35.100 +00:00 [INF] - Entering connected state
2018-09-11 12:34:34.987 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:35:34.988 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:36:34.992 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
2018-09-11 12:37:34.992 +00:00 [ERR] - Module iotedge-x64/sampledev is not connected
```

**Comment by LazarusX** [comment]
Thanks for reporting. Can you share the docker logs of other modules? Also, can you try creating a new Edge device and running `sudo iotedgedev setup` with the new device's connection string?

**Comment by mridup** [comment]
Logs for the tempSensor module:
`iotedgedev@9fbebd2eaead:/home/iotedge/sampledev$ sudo docker logs tempSensor
[2018-09-11 12:22:10 : Starting Module
[09/11/2018 12:22:10.810 PM] Main()
Using transport Amqp_Tcp_Only

Unhandled Exception: System.AggregateException: One or more errors occurred. (Put token failed. status-code: 400, status-description: Unable to authenticate iotedge-x64/tempSensor.) ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubException: Put token failed. status-code: 400, status-description: Unable to authenticate iotedge-x64/tempSensor.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType) in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 100
   at SimulatedTemperatureSensor.Program.MainAsync() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 69
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SimulatedTemperatureSensor.Program.Main() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 34
[2018-09-11 12:22:27 : Starting Module
[09/11/2018 12:22:27.366 PM] Main()
Using transport Amqp_Tcp_Only
Successfully initialized module client.
	09/11/2018 12:22:31> Sending message: 1, Body: [{"machine":{"temperature":22.156638531902171,"pressure":1.1317689466723992},"ambient":{"temperature":20.991380491988444,"humidity":24},"timeCreated":"2018-09-11T12:22:31.7041438Z"}]
	09/11/2018 12:22:37> Sending message: 2, Body: [{"machine":{"temperature":22.811352799791543,"pressure":1.2063566480775174},"ambient":{"temperature":20.703520989605934,"humidity":24},"timeCreated":"2018-09-11T12:22:37.2153586Z"}]
	09/11/2018 12:22:42> Sending message: 3, Body: [{"machine":{"temperature":22.73195728449242,"pressure":1.1973115893725541},"ambient":{"temperature":21.171464796025056,"humidity":25},"timeCreated":"2018-09-11T12:22:42.2390668Z"}]
	09/11/2018 12:22:47> Sending message: 4, Body: [{"machine":{"temperature":23.298141766711204,"pressure":1.2618136189924156},"ambient":{"temperature":20.694551336669619,"humidity":25},"timeCreated":"2018-09-11T12:22:47.2616732Z"}]
	09/11/2018 12:22:52> Sending message: 5, Body: [{"machine":{"temperature":23.685870007349116,"pressure":1.3059851907106588},"ambient":{"temperature":21.020169695615849,"humidity":25},"timeCreated":"2018-09-11T12:22:52.2841656Z"}]
	09/11/2018 12:22:57> Sending message: 6, Body: [{"machine":{"temperature":24.740108725260992,"pressure":1.4260883357892269},"ambient":{"temperature":20.742691446208717,"humidity":24},"timeCreated":"2018-09-11T12:22:57.3085247Z"}]
	09/11/2018 12:23:02> Sending message: 7, Body: [{"machine":{"temperature":25.10657806361866,"pressure":1.4678380072476953},"ambient":{"temperature":20.959751829253396,"humidity":24},"timeCreated":"2018-09-11T12:23:02.3320256Z"}]
	09/11/2018 12:23:07> Sending message: 8, Body: [{"machine":{"temperature":26.070927883531397,"pressure":1.577700644959273},"ambient":{"temperature":21.394428218200069,"humidity":26},"timeCreated":"2018-09-11T12:23:07.3546705Z"}]
	09/11/2018 12:23:12> Sending message: 9, Body: [{"machine":{"temperature":26.242127897447034,"pressure":1.5972044440129531},"ambient":{"temperature":20.511201012884825,"humidity":26},"timeCreated":"2018-09-11T12:23:12.3773757Z"}]
	09/11/2018 12:23:17> Sending message: 10, Body: [{"machine":{"temperature":27.459299512887046,"pressure":1.7358695647592839},"ambient":{"temperature":20.8686595607403,"humidity":26},"timeCreated":"2018-09-11T12:23:17.4000753Z"}]
`

**Comment by mridup** [comment]
logs for the custom python module (sampledev):

`iotedgedev@9fbebd2eaead:/home/iotedge/sampledev$ sudo docker logs sampledev

Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]

IoT Hub Client for Python
Starting the IoT Hub Python sample using protocol MQTT...
The sample is now waiting for messages and will indefinitely.  Press Ctrl-C to exit. 
Error: Time:Tue Sep 11 12:22:11 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:383 Failure: connect failure 111.
Error: Time:Tue Sep 11 12:22:11 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:767 wait_for_connection failed
Error: Time:Tue Sep 11 12:22:11 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:748 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Tue Sep 11 12:22:11 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1246 Failed opening the underlying I/O.
Error: Time:Tue Sep 11 12:22:11 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:989 Error: io_open failed
Error: Time:Tue Sep 11 12:22:11 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2037 failure connecting to address 9fbebd2eaead.
Error: Time:Tue Sep 11 12:22:12 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:383 Failure: connect failure 111.
Error: Time:Tue Sep 11 12:22:12 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:767 wait_for_connection failed
Error: Time:Tue Sep 11 12:22:12 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:748 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Tue Sep 11 12:22:12 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1246 Failed opening the underlying I/O.
Error: Time:Tue Sep 11 12:22:12 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:989 Error: io_open failed
Error: Time:Tue Sep 11 12:22:12 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2037 failure connecting to address 9fbebd2eaead.
Error: Time:Tue Sep 11 12:22:14 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:383 Failure: connect failure 111.
Error: Time:Tue Sep 11 12:22:14 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:767 wait_for_connection failed
Error: Time:Tue Sep 11 12:22:14 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:748 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Tue Sep 11 12:22:14 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1246 Failed opening the underlying I/O.
Error: Time:Tue Sep 11 12:22:14 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:989 Error: io_open failed
Error: Time:Tue Sep 11 12:22:14 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2037 failure connecting to address 9fbebd2eaead.
Error: Time:Tue Sep 11 12:22:18 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:661 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Error: Time:Tue Sep 11 12:22:26 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:661 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Error: Time:Tue Sep 11 12:22:42 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:661 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Error: Time:Tue Sep 11 12:23:14 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:661 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Error: Time:Tue Sep 11 12:24:20 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:661 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Error: Time:Tue Sep 11 12:26:31 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:661 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Error: Time:Tue Sep 11 12:30:54 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:661 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Error: Time:Tue Sep 11 12:39:50 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:661 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Error: Time:Tue Sep 11 12:57:31 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:661 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Error: Time:Tue Sep 11 14:01:16 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:661 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed`

**Comment by mridup** [comment]
the edge device is actually an AWS ec2 instance. It could also be that I may have forgotten to enable all required ports with necessary protocols?

**Comment by LazarusX** [comment]
This is a know issue with the IoT Edge Simulator: it does not support running Python modules and C modules yet. See https://github.com/Azure/iotedgehubdev/issues/67.

I will update the document to note this.

**Comment by mridup** [comment]
thanks for the confirmation @LazarusX
