### ISSUE TITLE
Support Dockerfiles that aren't in module project root

### ISSUE THREAD

**Issue by rahulrai-in** [Azure/iotedgedev#33]
I added a few modules in the module folder and modified the module.json file to point to the Dockerfile as below. 
{
    "$schema-version": "0.0.1",
    "description": "",
    "image": {
        "repository": "<registry>/<repo-name>",
        "tag": {
            "version": "0.0.1",
            "platforms": {
                "linuxx64": "/Docker/linux-x64/Dockerfile"
            }
        }
    },
    "language": "csharp"
}

When I try to build this module using the command `iotedgedev modules --build` I get the error that Dockerfile was not found with the stack trace below:

Traceback (most recent call last):
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\docker\api\client.py", line 222, in _raise_for_status
    response.raise_for_status()
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/v1.30/build?t=dummyreg.azurecr.io%2Fbatchingmodule%3A0.0.1-linuxx64&q=False&nocache=False&rm=False&forcerm=False&pull=False&dockerfile=Dockerfile&buildargs=%7B%22EXE_DIR%22%3A+%22.%2Fbin%2FDebug%2Fnetcoreapp2.0%2Fpublish%22%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\rahul\AppData\Local\Programs\Python\Python36-32\Scripts\iotedgedev.exe\__main__.py", line 9, in <module>
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\iotedgedev\cli.py", line 324, in modules
    mod.build()
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\iotedgedev\modules.py", line 80, in build
    tag=image_destination_name, path=".", dockerfile=docker_file_name, buildargs={"EXE_DIR": mod_proc.exe_dir})
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\docker\models\images.py", line 177, in build
    for chunk in json_stream(resp):
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\docker\utils\json_stream.py", line 66, in split_buffer
    for data in stream_as_text(stream):
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\docker\utils\json_stream.py", line 22, in stream_as_text
    for data in stream:
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\docker\api\client.py", line 313, in _stream_helper
    yield self._result(response, json=decode)
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\docker\api\client.py", line 228, in _result
    self._raise_for_status(response)
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\docker\api\client.py", line 224, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "c:\users\rahul\appdata\local\programs\python\python36-32\lib\site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Cannot locate specified Dockerfile: Dockerfile")

**Comment by jonbgallant** [comment]
Please put Dockerfile in root of module for now. 

For dev: Add support for docker file in any subfolder.

**Comment by aminespinoza** [comment]
Got it.

**Comment by LazarusX** [comment]
#194 adds support for this scenario. Next release should be in a couple of weeks.

**Comment by jongio** [comment]
@LazarusX - Closing this as fixed in next release.
