### ISSUE TITLE
KeyError: 'cs' in azurecli.py

### ISSUE THREAD

**Issue by jporcenaluk** [Azure/iotedgedev#387]
There is an issue (Windows 10, python 3.7, Azure CLI) where when I run the setup, I am greeted with the following output:

```
Traceback (most recent call last):
  File "c:\users\jporc\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jporc\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jporc\AppData\Local\Programs\Python\Python37-32\Scripts\iotedgedev.exe\__main__.py", line 9, in <module>
  File "c:\users\jporc\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\jporc\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\jporc\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\jporc\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1135, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "c:\users\jporc\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "c:\users\jporc\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "c:\users\jporc\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1477, in handle_parse_result
    self.callback, ctx, self, value)
  File "c:\users\jporc\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "c:\users\jporc\appdata\local\programs\python\python37-32\lib\site-packages\iotedgedev\cli.py", line 497, in validate_option
    envvars.DEVICE_CONNECTION_STRING = azure_cli.get_device_connection_string(envvars.EDGE_DEVICE_ID, envvars.IOTHUB_NAME, envvars.RESOURCE_GROUP_NAME)
  File "c:\users\jporc\appdata\local\programs\python\python37-32\lib\site-packages\iotedgedev\azurecli.py", line 501, in get_device_connection_string
    return data["cs"]
KeyError: 'cs'
```
It turns out that the key here is not 'cs', but instead 'connectionString'

**Comment by nouira** [comment]
I'm still getting this error with the latest docker image.
Is there a work around or a tag for a new image version ?

`Traceback (most recent call last):
  File "/usr/local/bin/iotedgedev", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1135, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1477, in handle_parse_result
    self.callback, ctx, self, value)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/local/lib/python3.6/dist-packages/iotedgedev/cli.py", line 496, in validate_option
    envvars.IOTHUB_CONNECTION_STRING = azure_cli.get_iothub_connection_string(envvars.IOTHUB_NAME, envvars.RESOURCE_GROUP_NAME)
  File "/usr/local/lib/python3.6/dist-packages/iotedgedev/azurecli.py", line 455, in get_iothub_connection_string
    return data["cs"]
KeyError: 'cs'`
