### ISSUE TITLE
[BUG] "iotedgedev solution init" fails if az cli default output is not set to json

### ISSUE THREAD

**Issue by marcgs** [Azure/iotedgedev#597]
### Description

Running `iotedgedev solution init` after following the [manual prerequisites setup](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-vs-code-develop-module?view=iotedge-1.4&tabs=csharp&pivots=iotedge-dev-cli#prerequisites) and with az cli default output set to "table" generates the following error output after all available Azure subscriptions are listed:

```
Traceback (most recent call last):
  File "/usr/local/bin/iotedgedev", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1655, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 2356, in handle_parse_result
    value, source = self.consume_value(ctx, opts)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 2890, in consume_value
    value, source = super().consume_value(ctx, opts)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 2251, in consume_value
    value = self.get_default(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 2824, in get_default
    return super().get_default(ctx, call=call)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 2229, in get_default
    value = value()
  File "/usr/local/lib/python3.10/site-packages/iotedgedev/cli.py", line 586, in <lambda>
    default=lambda: list_subscriptions_and_set_default(),
  File "/usr/local/lib/python3.10/site-packages/iotedgedev/cli.py", line 554, in list_subscriptions_and_set_default
    default_subscriptionId = azure_cli.get_default_subscription()
  File "/usr/local/lib/python3.10/site-packages/iotedgedev/azurecli.py", line 269, in get_default_subscription
    data = json.loads(out_string)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR: Error while executing command: iotedgedev iothub setup --update-dotenv. Command '['iotedgedev', 'iothub', 'setup', '--update-dotenv']' returned non-zero exit status 1.
```

Probably calls to the az cli should specify `--out json` output to prevent this issue. 

### Expected behavior

User should be able to proceed with the selection of the corresponding subscription so that Azure resources can be created.

### Actual behavior

Command fails with the mentioned error.

### Steps to Reproduce

1. `az configure` and set the default output to `table`
2. `iotedgedev solution init`

### Environment

iotedge 2.1.0
python 3.10.8
pip 22.2.2
macOs Monterey 12.6.1

**Comment by roel4ez** [comment]
@marcgs fixed and should be part of the next release. Thanks for reporting!
