### ISSUE TITLE
dependency missing "Click"[BUG] 

### ISSUE THREAD

**Issue by LaudixGit** [Azure/iotedgedev#610]
### Description

[This ](iotedgedev/cli.py)uses Click.
However, on a Raspberry Pi 4 with latest OS "Linux RPi4-Alpha 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux"

Running command `iotedgedev init --template python LED` **fails** with error:

> ModuleNotFoundError: No module named 'click'

### Expected behavior

installer should include all dependancies

`sudo pip3 install -U iotedgedev`

### Actual behavior

as-is install not usable

### Steps to Reproduce

Follow [these steps](https://github.com/Azure/iotedgedev/blob/main/docs/environment-setup/manual-dev-machine-setup.md).

attempt to begin new project:
`iotedgedev init --template python LED`

### Environment

$ uname -a
Linux RPi4-Alpha 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
$ python --version
Python 3.9.2
$ pip --version
pip 23.2.1 from /home/inc/.local/lib/python3.9/site-packages/pip (python 3.9)
$ iotedgedev -- version
Traceback (most recent call last):
  File "/usr/local/bin/iotedgedev", line 5, in <module>
    from iotedgedev.cli import main
  File "/usr/local/lib/python3.9/dist-packages/iotedgedev/cli.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'

**Comment by LaudixGit** [comment]
see #611 for inability to install missing dependency
