### ISSUE TITLE
[BUG] No module named 'urllib3.packages.six.moves'

### ISSUE THREAD

**Issue by codeminic** [Azure/iotedgedev#614]
### Description

When running any `iotedgedev` command, I get the following error:
```
No module named 'urllib3.packages.six.moves'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\domin\AppData\Local\Programs\Python\Python312\Scripts\iotedgedev.exe\__main__.py", line 4, in <module>
  File "C:\Users\domin\AppData\Local\Programs\Python\Python312\Lib\site-packages\iotedgedev\cli.py", line 14, in <module>
    from .dockercls import Docker
  File "C:\Users\domin\AppData\Local\Programs\Python\Python312\Lib\site-packages\iotedgedev\dockercls.py", line 4, in <module>
    import docker
  File "C:\Users\domin\AppData\Local\Programs\Python\Python312\Lib\site-packages\docker\__init__.py", line 2, in <module>
    from .api import APIClient
  File "C:\Users\domin\AppData\Local\Programs\Python\Python312\Lib\site-packages\docker\api\__init__.py", line 2, in <module>
    from .client import APIClient
  File "C:\Users\domin\AppData\Local\Programs\Python\Python312\Lib\site-packages\docker\api\client.py", line 5, in <module>
    import requests
  File "C:\Users\domin\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\domin\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Users\domin\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Users\domin\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

### Expected behavior

The command does not fail 😉

### Actual behavior

The command fails with the above mentioned error

### Steps to Reproduce

* Install the iotedgedev tool according to the setup steps from the Wiki
* Run any `iotedgedev` command 

### Environment

iotedgedev: 2.1.0
python: 3.12.0
pip: 23.3.1
Dev OS: Windows 11 Pro 23H2

**Comment by ccPB29** [comment]
same error……

**Comment by ccPB29** [comment]
I solved it when i change my python version 12->10

**Comment by konichi3** [comment]
Our latest version of Python is v3.9. Thanks for the update.
