### ISSUE TITLE
iotedgedev simulator setup giving AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'

### ISSUE THREAD

**Issue by gopimails** [Azure/iotedgedev#625]
While doing iotedgedev simulator setup, it give error **AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'**

**iotedgedev simulator setup**

Environment Variables loaded from: .env (/workspaces/xxxx/xxx/xx/.env)

SETTING UP IOT EDGE SIMULATOR

ERROR: Traceback (most recent call last):
  File "/usr/local/python/current/bin/iotedgehubdev", line 5, in <module>
    from iotedgehubdev.cli import main
  File "/usr/local/python/3.9.19/lib/python3.9/site-packages/iotedgehubdev/cli.py", line 15, in <module>
    from .edgecert import EdgeCert
  File "/usr/local/python/3.9.19/lib/python3.9/site-packages/iotedgehubdev/edgecert.py", line 4, in <module>
    from .certutils import EdgeCertUtil
  File "/usr/local/python/3.9.19/lib/python3.9/site-packages/iotedgehubdev/certutils.py", line 6, in <module>
    from OpenSSL import crypto
  File "/usr/local/python/3.9.19/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/python/3.9.19/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1570, in <module>
    class X509StoreFlags(object):
  File "/usr/local/python/3.9.19/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1589, in X509StoreFlags
    **NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'**

- python --version (Python 3.9.19)
- pip --version (pip 24.0 from /usr/local/python/3.9.19/lib/python3.9/site-packages/pip (python 3.9))
- iotedgedev, version 3.3.7
- openssl version: OpenSSL 1.1.1w  11 Sep 2023
- devcontainer: mcr.microsoft.com/vscode/devcontainers/base:bullseye

**Comment by gopimails** [comment]
I replaced devcontainer with "mcr.microsoft.com/iotedge/iotedgedev:latest"

Things are good now: 
python --version Python 2.7.18
iotedgedev, version 3.3.7
openssl version OpenSSL 1.1.1f  31 Mar 2020
